name = "PeaceFounder"
uuid = "916f7771-afe2-4319-943d-0e770c333432"
authors = ["Janis Erdmanis <janiserdmanis@protonmail.ch>"]
version = "0.4.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CryptoGroups = "bc997328-bedd-407e-bcd3-5758e064a52d"
CryptoSignatures = "35cc5888-0c46-470e-89c7-eafcaf79a1aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HistoryTrees = "6629d18c-a67a-486a-9b40-962f9d752038"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
ShuffleProofs = "31a120cc-b3cb-4d07-bbdb-d498660ddfd8"
StructHelpers = "4093c41a-2008-41fd-82b8-e3f9d02b504f"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
SwaggerMarkdown = "1b6eb727-ad4b-44eb-9669-b9596a6e760f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
CryptoGroups = "0.4"
CryptoSignatures = "0.3"
HTTP = "1"
HistoryTrees = "0.2"
JSON3 = "1"
Nettle = "1"
Setfield = "1"
ShuffleProofs = "0.3"
StructTypes = "1"
URIs = "1.4"
julia = "1"
StructHelpers = "1.1"